---
i3wm:
    - alsa-utils
    - arandr
    - feh
    - i3-wm
    - i3status
    - i3blocks
    - nitrogen
    - network-manager-gnome
    - network-manager  
    - picom
    - playerctl
    - rofi
    - fonts-font-awesome

i3lockcolor_dep:
    - autoconf
    - gcc
    - make
    - pkg-config
    - libpam0g-dev
    - libcairo2-dev
    - libfontconfig1-dev
    - libxcb-composite0-dev
    - libev-dev
    - libx11-xcb-dev
    - libxcb-xkb-dev
    - libxcb-xinerama0-dev
    - libxcb-randr0-dev
    - libxcb-image0-dev
    - libxcb-util0-dev
    - libxcb-xrm-dev
    - libxcb-xtest0-dev
    - libxkbcommon-dev
    - libxkbcommon-x11-dev
    - libjpeg-dev
