---
- name: Install packages
  apt: name={{item}} state=present update_cache=true
  with_items:
       - ['{{ themes }}']
       - ['{{ desktop_utilities }}']
       - ['{{ accessories }}']
       - ['{{ clients }}']
       - ['{{ games }}']
       - ['{{ bash }}']
       - ['{{ fonts }}']
       - ['{{ sys }}']

- name: Remove packages
  apt: name={{item}} state=absent
  with_items:
       - ['{{ firefox_lang }}']
       - ['{{ blacklist }}']
       - ['{{ cinnamon_games }}']
