---
- name: i3wm_legacy tasks
  tags: i3wm_legacy
  block:
  - name: Install packages
    apt: name={{item}} state=present update_cache=true
    with_items:
      - ['{{ i3wm }}']
  
  - name: Create xinitrc file
    copy:
      src: files/xinitrc
      dest: "{{ user.home }}/.xinitrc"
      owner: "{{ user.name }}"
      group: "{{ user.name }}"
      mode: '0644'
  
  - name: Creates directory xorg.conf.d in /etc/X11/
    file:
      path: /etc/X11/xorg.conf.d
      state: directory
      owner: root
      group: root
      mode: 0755
  
  - name: Copy 90-touchpad.conf in /etc/X11/xorg.conf.d/
    copy:
      src: files/90-touchpad.conf
      dest: /etc/X11/xorg.conf.d
      owner: root
      group: root
      mode: '0644'
