---
- name: Install packages
  apt: name={{item}} state=present update_cache=true
  with_items:
    - ['{{ i3wm }}']

- name: Create xinitrc file
  copy:
    src: files/xinitrc
    dest: "{{ user.home }}/.xinitrc"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0644'

- name: Clone a github repository
  git:
    repo: https://github.com/vivien/i3blocks-contrib
    dest: "{{ user.home }}/.config/i3blocks-contrib"
    clone: yes
    update: yes

- name: Clone github repo i3lock-color
  git:
    repo: https://github.com/Raymo111/i3lock-color
    dest: "{{ user.home }}"
    clone: yes
    update: yes

- name: compile and install i3lock-color
  become: yes
  become_user: "{{ user.name }}"
  shell:  cd "{{ user.home }}/i3lock-color" && ./build.sh && ./install-i3lock-color.sh

- name: NetworkManager service enable
  become: yes
  become_user: root
  become_method: sudo

  systemd:
    name: NetworkManager
    state: started
    enabled: yes

